// Mocks generated by Mockito 5.4.4 from annotations
// in linfa/test/screen/plant_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:linfa/data/database/database.dart' as _i2;
import 'package:linfa/data/models/growth_entry.dart' as _i6;
import 'package:linfa/data/models/plant.dart' as _i5;
import 'package:linfa/data/models/reminder.dart' as _i8;
import 'package:linfa/data/repositories/plant_repository.dart' as _i3;
import 'package:linfa/data/repositories/reminder_repository.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabaseService_0 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlantRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantRepository extends _i1.Mock implements _i3.PlantRepository {
  MockPlantRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get databaseService => (super.noSuchMethod(
        Invocation.getter(#databaseService),
        returnValue: _FakeDatabaseService_0(
          this,
          Invocation.getter(#databaseService),
        ),
      ) as _i2.DatabaseService);

  @override
  _i4.Future<List<_i5.Plant>> getAllPlants({bool? includeArchived = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPlants,
          [],
          {#includeArchived: includeArchived},
        ),
        returnValue: _i4.Future<List<_i5.Plant>>.value(<_i5.Plant>[]),
      ) as _i4.Future<List<_i5.Plant>>);

  @override
  _i4.Future<List<_i5.Plant>> getPlantsByRoom(String? room) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantsByRoom,
          [room],
        ),
        returnValue: _i4.Future<List<_i5.Plant>>.value(<_i5.Plant>[]),
      ) as _i4.Future<List<_i5.Plant>>);

  @override
  _i4.Future<List<String>> getAllRooms() => (super.noSuchMethod(
        Invocation.method(
          #getAllRooms,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<_i5.Plant?> getPlant(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getPlant,
          [id],
        ),
        returnValue: _i4.Future<_i5.Plant?>.value(),
      ) as _i4.Future<_i5.Plant?>);

  @override
  _i4.Future<List<_i5.Plant>> searchPlants(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPlants,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.Plant>>.value(<_i5.Plant>[]),
      ) as _i4.Future<List<_i5.Plant>>);

  @override
  _i4.Future<int> addPlant(_i5.Plant? plant) => (super.noSuchMethod(
        Invocation.method(
          #addPlant,
          [plant],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> updatePlant(_i5.Plant? plant) => (super.noSuchMethod(
        Invocation.method(
          #updatePlant,
          [plant],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deletePlant(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePlant,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> archivePlant(int? id) => (super.noSuchMethod(
        Invocation.method(
          #archivePlant,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleFavorite(int? id) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> recordWatering(int? id) => (super.noSuchMethod(
        Invocation.method(
          #recordWatering,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> recordFertilizing(int? id) => (super.noSuchMethod(
        Invocation.method(
          #recordFertilizing,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> recordMisting(int? id) => (super.noSuchMethod(
        Invocation.method(
          #recordMisting,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> recordRepotting(int? id) => (super.noSuchMethod(
        Invocation.method(
          #recordRepotting,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> recordPruning(int? id) => (super.noSuchMethod(
        Invocation.method(
          #recordPruning,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> recordCleaning(int? id) => (super.noSuchMethod(
        Invocation.method(
          #recordCleaning,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Plant>> getPlantsNeedingWater(int? defaultDays) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantsNeedingWater,
          [defaultDays],
        ),
        returnValue: _i4.Future<List<_i5.Plant>>.value(<_i5.Plant>[]),
      ) as _i4.Future<List<_i5.Plant>>);

  @override
  _i4.Future<int> getPlantCount() => (super.noSuchMethod(
        Invocation.method(
          #getPlantCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> exportAllPlants() =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAllPlants,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> importPlants(List<Map<String, dynamic>>? plantsJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #importPlants,
          [plantsJson],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addGrowthEntry(
    int? plantId,
    _i6.GrowthEntry? entry,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addGrowthEntry,
          [
            plantId,
            entry,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.GrowthEntry>> getGrowthEntries(int? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGrowthEntries,
          [plantId],
        ),
        returnValue:
            _i4.Future<List<_i6.GrowthEntry>>.value(<_i6.GrowthEntry>[]),
      ) as _i4.Future<List<_i6.GrowthEntry>>);
}

/// A class which mocks [ReminderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReminderRepository extends _i1.Mock
    implements _i7.ReminderRepository {
  MockReminderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get databaseService => (super.noSuchMethod(
        Invocation.getter(#databaseService),
        returnValue: _FakeDatabaseService_0(
          this,
          Invocation.getter(#databaseService),
        ),
      ) as _i2.DatabaseService);

  @override
  _i4.Future<List<_i8.Reminder>> getAllReminders() => (super.noSuchMethod(
        Invocation.method(
          #getAllReminders,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Reminder>>.value(<_i8.Reminder>[]),
      ) as _i4.Future<List<_i8.Reminder>>);

  @override
  _i4.Future<List<_i8.Reminder>> getRemindersForPlant(int? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemindersForPlant,
          [plantId],
        ),
        returnValue: _i4.Future<List<_i8.Reminder>>.value(<_i8.Reminder>[]),
      ) as _i4.Future<List<_i8.Reminder>>);

  @override
  _i4.Future<List<_i8.Reminder>> getActiveReminders() => (super.noSuchMethod(
        Invocation.method(
          #getActiveReminders,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Reminder>>.value(<_i8.Reminder>[]),
      ) as _i4.Future<List<_i8.Reminder>>);

  @override
  _i4.Future<List<_i8.Reminder>> getOverdueReminders() => (super.noSuchMethod(
        Invocation.method(
          #getOverdueReminders,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Reminder>>.value(<_i8.Reminder>[]),
      ) as _i4.Future<List<_i8.Reminder>>);

  @override
  _i4.Future<List<_i8.Reminder>> getTodayReminders() => (super.noSuchMethod(
        Invocation.method(
          #getTodayReminders,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Reminder>>.value(<_i8.Reminder>[]),
      ) as _i4.Future<List<_i8.Reminder>>);

  @override
  _i4.Future<List<_i8.Reminder>> getUpcomingReminders() => (super.noSuchMethod(
        Invocation.method(
          #getUpcomingReminders,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Reminder>>.value(<_i8.Reminder>[]),
      ) as _i4.Future<List<_i8.Reminder>>);

  @override
  _i4.Future<_i8.Reminder?> getReminder(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getReminder,
          [id],
        ),
        returnValue: _i4.Future<_i8.Reminder?>.value(),
      ) as _i4.Future<_i8.Reminder?>);

  @override
  _i4.Future<int> addReminder(_i8.Reminder? reminder) => (super.noSuchMethod(
        Invocation.method(
          #addReminder,
          [reminder],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> updateReminder(_i8.Reminder? reminder) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReminder,
          [reminder],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteReminder(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteReminder,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleEnabled(int? id) => (super.noSuchMethod(
        Invocation.method(
          #toggleEnabled,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markTriggered(int? id) => (super.noSuchMethod(
        Invocation.method(
          #markTriggered,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getReminderCount() => (super.noSuchMethod(
        Invocation.method(
          #getReminderCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> exportAllReminders() =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAllReminders,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> importReminders(List<Map<String, dynamic>>? remindersJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #importReminders,
          [remindersJson],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
