// Mocks generated by Mockito 5.4.4 from annotations
// in linfa/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i17;

import 'package:flutter/foundation.dart' as _i6;
import 'package:flutter/material.dart' as _i5;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i18;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i13;
import 'package:isar/isar.dart' as _i3;
import 'package:linfa/core/constants/enums.dart' as _i16;
import 'package:linfa/data/database/database.dart' as _i2;
import 'package:linfa/data/models/growth_entry.dart' as _i10;
import 'package:linfa/data/models/plant.dart' as _i9;
import 'package:linfa/data/models/reminder.dart' as _i12;
import 'package:linfa/data/repositories/plant_repository.dart' as _i7;
import 'package:linfa/data/repositories/reminder_repository.dart' as _i11;
import 'package:linfa/shared/providers/notification_provider.dart' as _i4;
import 'package:linfa/shared/providers/theme_provider.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i14;
import 'package:timezone/timezone.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabaseService_0 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIsar_1 extends _i1.SmartFake implements _i3.Isar {
  _FakeIsar_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationSettings_2 extends _i1.SmartFake
    implements _i4.NotificationSettings {
  _FakeNotificationSettings_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeData_3 extends _i1.SmartFake implements _i5.ThemeData {
  _FakeThemeData_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i6.DiagnosticLevel? minLevel = _i6.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [PlantRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantRepository extends _i1.Mock implements _i7.PlantRepository {
  MockPlantRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get databaseService => (super.noSuchMethod(
        Invocation.getter(#databaseService),
        returnValue: _FakeDatabaseService_0(
          this,
          Invocation.getter(#databaseService),
        ),
      ) as _i2.DatabaseService);

  @override
  _i8.Future<List<_i9.Plant>> getAllPlants({bool? includeArchived = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPlants,
          [],
          {#includeArchived: includeArchived},
        ),
        returnValue: _i8.Future<List<_i9.Plant>>.value(<_i9.Plant>[]),
      ) as _i8.Future<List<_i9.Plant>>);

  @override
  _i8.Future<List<_i9.Plant>> getPlantsByRoom(String? room) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantsByRoom,
          [room],
        ),
        returnValue: _i8.Future<List<_i9.Plant>>.value(<_i9.Plant>[]),
      ) as _i8.Future<List<_i9.Plant>>);

  @override
  _i8.Future<List<String>> getAllRooms() => (super.noSuchMethod(
        Invocation.method(
          #getAllRooms,
          [],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<_i9.Plant?> getPlant(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getPlant,
          [id],
        ),
        returnValue: _i8.Future<_i9.Plant?>.value(),
      ) as _i8.Future<_i9.Plant?>);

  @override
  _i8.Future<List<_i9.Plant>> searchPlants(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPlants,
          [query],
        ),
        returnValue: _i8.Future<List<_i9.Plant>>.value(<_i9.Plant>[]),
      ) as _i8.Future<List<_i9.Plant>>);

  @override
  _i8.Future<int> addPlant(_i9.Plant? plant) => (super.noSuchMethod(
        Invocation.method(
          #addPlant,
          [plant],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> updatePlant(_i9.Plant? plant) => (super.noSuchMethod(
        Invocation.method(
          #updatePlant,
          [plant],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deletePlant(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePlant,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> archivePlant(int? id) => (super.noSuchMethod(
        Invocation.method(
          #archivePlant,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> toggleFavorite(int? id) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> recordWatering(int? id) => (super.noSuchMethod(
        Invocation.method(
          #recordWatering,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> recordFertilizing(int? id) => (super.noSuchMethod(
        Invocation.method(
          #recordFertilizing,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> recordMisting(int? id) => (super.noSuchMethod(
        Invocation.method(
          #recordMisting,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> recordRepotting(int? id) => (super.noSuchMethod(
        Invocation.method(
          #recordRepotting,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> recordPruning(int? id) => (super.noSuchMethod(
        Invocation.method(
          #recordPruning,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> recordCleaning(int? id) => (super.noSuchMethod(
        Invocation.method(
          #recordCleaning,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i9.Plant>> getPlantsNeedingWater(int? defaultDays) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantsNeedingWater,
          [defaultDays],
        ),
        returnValue: _i8.Future<List<_i9.Plant>>.value(<_i9.Plant>[]),
      ) as _i8.Future<List<_i9.Plant>>);

  @override
  _i8.Future<int> getPlantCount() => (super.noSuchMethod(
        Invocation.method(
          #getPlantCount,
          [],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<Map<String, dynamic>>> exportAllPlants() =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAllPlants,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> importPlants(List<Map<String, dynamic>>? plantsJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #importPlants,
          [plantsJson],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addGrowthEntry(
    int? plantId,
    _i10.GrowthEntry? entry,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addGrowthEntry,
          [
            plantId,
            entry,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i10.GrowthEntry>> getGrowthEntries(int? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGrowthEntries,
          [plantId],
        ),
        returnValue:
            _i8.Future<List<_i10.GrowthEntry>>.value(<_i10.GrowthEntry>[]),
      ) as _i8.Future<List<_i10.GrowthEntry>>);
}

/// A class which mocks [ReminderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReminderRepository extends _i1.Mock
    implements _i11.ReminderRepository {
  MockReminderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get databaseService => (super.noSuchMethod(
        Invocation.getter(#databaseService),
        returnValue: _FakeDatabaseService_0(
          this,
          Invocation.getter(#databaseService),
        ),
      ) as _i2.DatabaseService);

  @override
  _i8.Future<List<_i12.Reminder>> getAllReminders() => (super.noSuchMethod(
        Invocation.method(
          #getAllReminders,
          [],
        ),
        returnValue: _i8.Future<List<_i12.Reminder>>.value(<_i12.Reminder>[]),
      ) as _i8.Future<List<_i12.Reminder>>);

  @override
  _i8.Future<List<_i12.Reminder>> getRemindersForPlant(int? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRemindersForPlant,
          [plantId],
        ),
        returnValue: _i8.Future<List<_i12.Reminder>>.value(<_i12.Reminder>[]),
      ) as _i8.Future<List<_i12.Reminder>>);

  @override
  _i8.Future<List<_i12.Reminder>> getActiveReminders() => (super.noSuchMethod(
        Invocation.method(
          #getActiveReminders,
          [],
        ),
        returnValue: _i8.Future<List<_i12.Reminder>>.value(<_i12.Reminder>[]),
      ) as _i8.Future<List<_i12.Reminder>>);

  @override
  _i8.Future<List<_i12.Reminder>> getOverdueReminders() => (super.noSuchMethod(
        Invocation.method(
          #getOverdueReminders,
          [],
        ),
        returnValue: _i8.Future<List<_i12.Reminder>>.value(<_i12.Reminder>[]),
      ) as _i8.Future<List<_i12.Reminder>>);

  @override
  _i8.Future<List<_i12.Reminder>> getTodayReminders() => (super.noSuchMethod(
        Invocation.method(
          #getTodayReminders,
          [],
        ),
        returnValue: _i8.Future<List<_i12.Reminder>>.value(<_i12.Reminder>[]),
      ) as _i8.Future<List<_i12.Reminder>>);

  @override
  _i8.Future<List<_i12.Reminder>> getUpcomingReminders() => (super.noSuchMethod(
        Invocation.method(
          #getUpcomingReminders,
          [],
        ),
        returnValue: _i8.Future<List<_i12.Reminder>>.value(<_i12.Reminder>[]),
      ) as _i8.Future<List<_i12.Reminder>>);

  @override
  _i8.Future<_i12.Reminder?> getReminder(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getReminder,
          [id],
        ),
        returnValue: _i8.Future<_i12.Reminder?>.value(),
      ) as _i8.Future<_i12.Reminder?>);

  @override
  _i8.Future<int> addReminder(_i12.Reminder? reminder) => (super.noSuchMethod(
        Invocation.method(
          #addReminder,
          [reminder],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> updateReminder(_i12.Reminder? reminder) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReminder,
          [reminder],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteReminder(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteReminder,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> toggleEnabled(int? id) => (super.noSuchMethod(
        Invocation.method(
          #toggleEnabled,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> markTriggered(int? id) => (super.noSuchMethod(
        Invocation.method(
          #markTriggered,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<int> getReminderCount() => (super.noSuchMethod(
        Invocation.method(
          #getReminderCount,
          [],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<Map<String, dynamic>>> exportAllReminders() =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAllReminders,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> importReminders(List<Map<String, dynamic>>? remindersJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #importReminders,
          [remindersJson],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i2.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i3.Isar get isar => (super.noSuchMethod(
        Invocation.getter(#isar),
        returnValue: _FakeIsar_1(
          this,
          Invocation.getter(#isar),
        ),
      ) as _i3.Isar);

  @override
  _i8.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<int> getSize() => (super.noSuchMethod(
        Invocation.method(
          #getSize,
          [],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);
}

/// A class which mocks [NotificationNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationNotifier extends _i1.Mock
    implements _i4.NotificationNotifier {
  MockNotificationNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i13.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<_i4.NotificationSettings> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i8.Stream<_i4.NotificationSettings>.empty(),
      ) as _i8.Stream<_i4.NotificationSettings>);

  @override
  _i4.NotificationSettings get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeNotificationSettings_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.NotificationSettings);

  @override
  set state(_i4.NotificationSettings? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.NotificationSettings get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeNotificationSettings_2(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i4.NotificationSettings);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> toggleEnabled() => (super.noSuchMethod(
        Invocation.method(
          #toggleEnabled,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> toggleSound() => (super.noSuchMethod(
        Invocation.method(
          #toggleSound,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<int> scheduleReminder(
    _i12.Reminder? reminder,
    String? plantName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleReminder,
          [
            reminder,
            plantName,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> cancelNotification(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelNotification,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancelPlantReminders(List<_i12.Reminder>? reminders) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelPlantReminders,
          [reminders],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool updateShouldNotify(
    _i4.NotificationSettings? old,
    _i4.NotificationSettings? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i13.RemoveListener addListener(
    _i14.Listener<_i4.NotificationSettings>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i13.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ThemeNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeNotifier extends _i1.Mock implements _i15.ThemeNotifier {
  MockThemeNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i13.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<_i16.AppThemeMode> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i8.Stream<_i16.AppThemeMode>.empty(),
      ) as _i8.Stream<_i16.AppThemeMode>);

  @override
  _i16.AppThemeMode get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i16.AppThemeMode.system,
      ) as _i16.AppThemeMode);

  @override
  set state(_i16.AppThemeMode? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i16.AppThemeMode get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _i16.AppThemeMode.system,
      ) as _i16.AppThemeMode);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setTheme(_i16.AppThemeMode? theme) => (super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [theme],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i5.ThemeData getThemeData(_i17.Brightness? brightness) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThemeData,
          [brightness],
        ),
        returnValue: _FakeThemeData_3(
          this,
          Invocation.method(
            #getThemeData,
            [brightness],
          ),
        ),
      ) as _i5.ThemeData);

  @override
  _i17.Brightness getBrightness() => (super.noSuchMethod(
        Invocation.method(
          #getBrightness,
          [],
        ),
        returnValue: _i17.Brightness.dark,
      ) as _i17.Brightness);

  @override
  bool updateShouldNotify(
    _i16.AppThemeMode? old,
    _i16.AppThemeMode? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i13.RemoveListener addListener(
    _i14.Listener<_i16.AppThemeMode>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i13.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i18.FlutterLocalNotificationsPlugin {
  MockFlutterLocalNotificationsPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool?> initialize(
    _i18.InitializationSettings? initializationSettings, {
    _i18.DidReceiveNotificationResponseCallback?
        onDidReceiveNotificationResponse,
    _i18.DidReceiveBackgroundNotificationResponseCallback?
        onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [initializationSettings],
          {
            #onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
            #onDidReceiveBackgroundNotificationResponse:
                onDidReceiveBackgroundNotificationResponse,
          },
        ),
        returnValue: _i8.Future<bool?>.value(),
      ) as _i8.Future<bool?>);

  @override
  _i8.Future<_i18.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationAppLaunchDetails,
              [],
            ),
            returnValue: _i8.Future<_i18.NotificationAppLaunchDetails?>.value(),
          ) as _i8.Future<_i18.NotificationAppLaunchDetails?>);

  @override
  _i8.Future<void> show(
    int? id,
    String? title,
    String? body,
    _i18.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [
            id,
            title,
            body,
            notificationDetails,
          ],
          {#payload: payload},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancel(
    int? id, {
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [id],
          {#tag: tag},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i19.TZDateTime? scheduledDate,
    _i18.NotificationDetails? notificationDetails, {
    required _i18.UILocalNotificationDateInterpretation?
        uiLocalNotificationDateInterpretation,
    required _i18.AndroidScheduleMode? androidScheduleMode,
    String? payload,
    _i18.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #zonedSchedule,
          [
            id,
            title,
            body,
            scheduledDate,
            notificationDetails,
          ],
          {
            #uiLocalNotificationDateInterpretation:
                uiLocalNotificationDateInterpretation,
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i18.RepeatInterval? repeatInterval,
    _i18.NotificationDetails? notificationDetails, {
    required _i18.AndroidScheduleMode? androidScheduleMode,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShow,
          [
            id,
            title,
            body,
            repeatInterval,
            notificationDetails,
          ],
          {
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> periodicallyShowWithDuration(
    int? id,
    String? title,
    String? body,
    Duration? repeatDurationInterval,
    _i18.NotificationDetails? notificationDetails, {
    _i18.AndroidScheduleMode? androidScheduleMode =
        _i18.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShowWithDuration,
          [
            id,
            title,
            body,
            repeatDurationInterval,
            notificationDetails,
          ],
          {
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i18.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
            Invocation.method(
              #pendingNotificationRequests,
              [],
            ),
            returnValue:
                _i8.Future<List<_i18.PendingNotificationRequest>>.value(
                    <_i18.PendingNotificationRequest>[]),
          ) as _i8.Future<List<_i18.PendingNotificationRequest>>);

  @override
  _i8.Future<List<_i18.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNotifications,
          [],
        ),
        returnValue: _i8.Future<List<_i18.ActiveNotification>>.value(
            <_i18.ActiveNotification>[]),
      ) as _i8.Future<List<_i18.ActiveNotification>>);
}
